services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "zaimik"
      POSTGRES_USER: "danzelVash"
      POSTGRES_PASSWORD: "22332223"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432"

  frontend:
    build: "./frontend"
    ports:
      - "3000"
    depends_on:
      - postgres

  app:
    build: "."
    ports:
      - "8080"
    depends_on:
      - frontend
    environment:
      db_host: postgres
    volumes:
      - ./logs:/app/logs

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./templates/css:/app/static/css
      - ./templates/img:/app/static/img
      - ./templates/js:/app/static/js