http:
  port: "8080"
  max_header_bytes: 1048576
  read_header_timeout: 4s
  read_timeout: 10s
  write_timeout: 10s

  protocol: "http://localhost:8080"
  domain: "localhost"

db:
  username: "danzelVash"
  host: "localhost"
  port: "5432"
  dbname: "zaimik"
  sslmode: "disable"

email:
  address: "zaimikbest@gmail.com"
